
def get_hfrs_weights() -> dict:
    """
    Returns the complete Hospital Frailty Risk Score (HFRS) weights dictionary
    from Gilbert et al. (2018), Table A2 (109 ICD-10 codes).

    Reference:
        Gilbert T, Neuburger J, Kraindler J, et al. Development and validation of a
        Hospital Frailty Risk Score focusing on older people in acute care settings
        using electronic hospital records: an observational study.
        Lancet. 2018;391(10132):1775-1782. doi:10.1016/S0140-6736(18)30668-8.

    Returns:
        dict: Mapping of ICD-10 cluster (3-4 characters) to metadata including points.
    """
    hfrs_weights = {
        'A04': {'ICD Description': 'Other bacterial intestinal infections',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 108,
             'Points awarded': 1.1,
             'devt percentage': 1.0,
             'frail percentage': 2.2},
        'A09': {'ICD Description': 'Diarrhoea and gastroenteritis of presumed',
             'Number with code in devt cohort': 1417,
             'Number with code in frail cohort': 618,
             'Points awarded': 1.1,
             'devt percentage': 6.4,
             'frail percentage': 12.6},
        'A41': {'ICD Description': 'Other septicaemia',
             'Number with code in devt cohort': 952,
             'Number with code in frail cohort': 515,
             'Points awarded': 1.6,
             'devt percentage': 4.3,
             'frail percentage': 10.5},
        'B95': {'ICD Description': 'Streptococcus and staphylococcus as the',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 182,
             'Points awarded': 1.7,
             'devt percentage': 1.5,
             'frail percentage': 3.7},
        'B96': {'ICD Description': 'Other bacterial agents as the cause of diseases',
             'Number with code in devt cohort': 1395,
             'Number with code in frail cohort': 918,
             'Points awarded': 2.9,
             'devt percentage': 6.3,
             'frail percentage': 18.7},
        'D64': {'ICD Description': 'Other anaemias',
             'Number with code in devt cohort': 2125,
             'Number with code in frail cohort': 829,
             'Points awarded': 0.4,
             'devt percentage': 9.6,
             'frail percentage': 16.9},
        'E05': {'ICD Description': 'Thyrotoxicosis [hyperthyroidism]',
             'Number with code in devt cohort': 199,
             'Number with code in frail cohort': 74,
             'Points awarded': 0.9,
             'devt percentage': 0.9,
             'frail percentage': 1.5},
        'E16': {'ICD Description': 'Other disorders of pancreatic internal',
             'Number with code in devt cohort': 421,
             'Number with code in frail cohort': 211,
             'Points awarded': 1.4,
             'devt percentage': 1.9,
             'frail percentage': 4.3},
        'E53': {'ICD Description': 'Deficiency of other B group vitamins',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 123,
             'Points awarded': 1.9,
             'devt percentage': 1.1,
             'frail percentage': 2.5},
        'E55': {'ICD Description': 'Vitamin D deficiency',
             'Number with code in devt cohort': 310,
             'Number with code in frail cohort': 157,
             'Points awarded': 1.0,
             'devt percentage': 1.4,
             'frail percentage': 3.2},
        'E83': {'ICD Description': 'Disorders of mineral metabolism',
             'Number with code in devt cohort': 288,
             'Number with code in frail cohort': 132,
             'Points awarded': 0.4,
             'devt percentage': 1.3,
             'frail percentage': 2.7},
        'E86': {'ICD Description': 'Volume depletion',
             'Number with code in devt cohort': 1550,
             'Number with code in frail cohort': 893,
             'Points awarded': 2.3,
             'devt percentage': 7.0,
             'frail percentage': 18.2},
        'E87': {'ICD Description': 'Other disorders of fluid, electrolyte and acid-',
             'Number with code in devt cohort': 2546,
             'Number with code in frail cohort': 1251,
             'Points awarded': 2.3,
             'devt percentage': 11.5,
             'frail percentage': 25.5},
        'F00': {'ICD Description': "Dementia in Alzheimer's disease",
             'Number with code in devt cohort': 664,
             'Number with code in frail cohort': 564,
             'Points awarded': 7.1,
             'devt percentage': 3.0,
             'frail percentage': 11.5},
        'F01': {'ICD Description': 'Vascular dementia',
             'Number with code in devt cohort': 863,
             'Number with code in frail cohort': 491,
             'Points awarded': 2.0,
             'devt percentage': 3.9,
             'frail percentage': 10.0},
        'F03': {'ICD Description': 'Unspecified dementia',
             'Number with code in devt cohort': 2701,
             'Number with code in frail cohort': 1433,
             'Points awarded': 2.1,
             'devt percentage': 12.2,
             'frail percentage': 29.2},
        'F05': {'ICD Description': 'Delirium, not induced by alcohol and other',
             'Number with code in devt cohort': 1328,
             'Number with code in frail cohort': 923,
             'Points awarded': 3.2,
             'devt percentage': 6.0,
             'frail percentage': 18.8},
        'F10': {'ICD Description': 'Mental and behavioural disorders due to use',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 93,
             'Points awarded': 0.7,
             'devt percentage': 1.0,
             'frail percentage': 1.9},
        'F32': {'ICD Description': 'Depressive episode',
             'Number with code in devt cohort': 1395,
             'Number with code in frail cohort': 613,
             'Points awarded': 0.5,
             'devt percentage': 6.3,
             'frail percentage': 12.5},
        'G20': {'ICD Description': "Parkinson's disease",
             'Number with code in devt cohort': 487,
             'Number with code in frail cohort': 240,
             'Points awarded': 1.8,
             'devt percentage': 2.2,
             'frail percentage': 4.9},
        'G30': {'ICD Description': "Alzheimer's disease",
             'Number with code in devt cohort': 1107,
             'Number with code in frail cohort': 751,
             'Points awarded': 4.0,
             'devt percentage': 5.0,
             'frail percentage': 15.3},
        'G31': {'ICD Description': 'Other degenerative diseases of nervous',
             'Number with code in devt cohort': 686,
             'Number with code in frail cohort': 417,
             'Points awarded': 1.2,
             'devt percentage': 3.1,
             'frail percentage': 8.5},
        'G40': {'ICD Description': 'Epilepsy',
             'Number with code in devt cohort': 443,
             'Number with code in frail cohort': 211,
             'Points awarded': 1.5,
             'devt percentage': 2.0,
             'frail percentage': 4.3},
        'G45': {'ICD Description': 'Transient cerebral ischaemic attacks and',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 88,
             'Points awarded': 1.2,
             'devt percentage': 1.1,
             'frail percentage': 1.8},
        'G81': {'ICD Description': 'Hemiplegia',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 240,
             'Points awarded': 4.4,
             'devt percentage': 1.5,
             'frail percentage': 4.9},
        'H54': {'ICD Description': 'Blindness and low vision',
             'Number with code in devt cohort': 642,
             'Number with code in frail cohort': 314,
             'Points awarded': 1.9,
             'devt percentage': 2.9,
             'frail percentage': 6.4},
        'H91': {'ICD Description': 'Other hearing loss',
             'Number with code in devt cohort': 1151,
             'Number with code in frail cohort': 466,
             'Points awarded': 0.9,
             'devt percentage': 5.2,
             'frail percentage': 9.5},
        'I63': {'ICD Description': 'Cerebral Infarction',
             'Number with code in devt cohort': 863,
             'Number with code in frail cohort': 324,
             'Points awarded': 0.8,
             'devt percentage': 3.9,
             'frail percentage': 6.6},
        'I67': {'ICD Description': 'Other cerebrovascular diseases',
             'Number with code in devt cohort': 1838,
             'Number with code in frail cohort': 1050,
             'Points awarded': 2.6,
             'devt percentage': 8.3,
             'frail percentage': 21.4},
        'I69': {'ICD Description': 'Sequelae of cerebrovascular disease',
             'Number with code in devt cohort': 509,
             'Number with code in frail cohort': 343,
             'Points awarded': 3.7,
             'devt percentage': 2.3,
             'frail percentage': 7.0},
        'I95': {'ICD Description': 'Hypotension',
             'Number with code in devt cohort': 1727,
             'Number with code in frail cohort': 844,
             'Points awarded': 1.6,
             'devt percentage': 7.8,
             'frail percentage': 17.2},
        'J18': {'ICD Description': 'Pneumonia, organism unspecified',
             'Number with code in devt cohort': 3830,
             'Number with code in frail cohort': 1644,
             'Points awarded': 1.1,
             'devt percentage': 17.3,
             'frail percentage': 33.5},
        'J22': {'ICD Description': 'Unspecified acute lower respiratory infection',
             'Number with code in devt cohort': 2059,
             'Number with code in frail cohort': 878,
             'Points awarded': 0.7,
             'devt percentage': 9.3,
             'frail percentage': 17.9},
        'J69': {'ICD Description': 'Pneumonitis due to solids and liquids',
             'Number with code in devt cohort': 487,
             'Number with code in frail cohort': 250,
             'Points awarded': 1.0,
             'devt percentage': 2.2,
             'frail percentage': 5.1},
        'J96': {'ICD Description': 'Respiratory failure, not elsewhere classified',
             'Number with code in devt cohort': 886,
             'Number with code in frail cohort': 353,
             'Points awarded': 1.5,
             'devt percentage': 4.0,
             'frail percentage': 7.2},
        'K26': {'ICD Description': 'Duodenal ulcer',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 98,
             'Points awarded': 1.6,
             'devt percentage': 1.1,
             'frail percentage': 2.0},
        'K52': {'ICD Description': 'Other noninfective gastroenteritis and colitis',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 93,
             'Points awarded': 0.3,
             'devt percentage': 1.1,
             'frail percentage': 1.9},
        'K59': {'ICD Description': 'Other functional intestinal disorders',
             'Number with code in devt cohort': 2590,
             'Number with code in frail cohort': 1305,
             'Points awarded': 1.8,
             'devt percentage': 11.7,
             'frail percentage': 26.6},
        'K92': {'ICD Description': 'Other diseases of digestive system',
             'Number with code in devt cohort': 1018,
             'Number with code in frail cohort': 388,
             'Points awarded': 0.8,
             'devt percentage': 4.6,
             'frail percentage': 7.9},
        'L03': {'ICD Description': 'Cellulitis',
             'Number with code in devt cohort': 863,
             'Number with code in frail cohort': 422,
             'Points awarded': 2.0,
             'devt percentage': 3.9,
             'frail percentage': 8.6},
        'L08': {'ICD Description': 'Other local infections of skin and',
             'Number with code in devt cohort': 155,
             'Number with code in frail cohort': 83,
             'Points awarded': 0.4,
             'devt percentage': 0.7,
             'frail percentage': 1.7},
        'L89': {'ICD Description': 'Decubitus ulcer',
             'Number with code in devt cohort': 775,
             'Number with code in frail cohort': 461,
             'Points awarded': 1.7,
             'devt percentage': 3.5,
             'frail percentage': 9.4},
        'L97': {'ICD Description': 'Ulcer of lower limb, not elsewhere classified',
             'Number with code in devt cohort': 797,
             'Number with code in frail cohort': 407,
             'Points awarded': 1.6,
             'devt percentage': 3.6,
             'frail percentage': 8.3},
        'M15': {'ICD Description': 'Polyarthrosis',
             'Number with code in devt cohort': 288,
             'Number with code in frail cohort': 113,
             'Points awarded': 0.4,
             'devt percentage': 1.3,
             'frail percentage': 2.3},
        'M19': {'ICD Description': 'Other arthrosis',
             'Number with code in devt cohort': 2635,
             'Number with code in frail cohort': 1040,
             'Points awarded': 1.5,
             'devt percentage': 11.9,
             'frail percentage': 21.2},
        'M25': {'ICD Description': 'Other joint disorders, not elsewhere classified',
             'Number with code in devt cohort': 1262,
             'Number with code in frail cohort': 648,
             'Points awarded': 2.3,
             'devt percentage': 5.7,
             'frail percentage': 13.2},
        'M41': {'ICD Description': 'Scoliosis',
             'Number with code in devt cohort': 288,
             'Number with code in frail cohort': 123,
             'Points awarded': 0.9,
             'devt percentage': 1.3,
             'frail percentage': 2.5},
        'M48': {'ICD Description': 'Spinal stenosis (secondary code only)',
             'Number with code in devt cohort': 487,
             'Number with code in frail cohort': 177,
             'Points awarded': 0.5,
             'devt percentage': 2.2,
             'frail percentage': 3.6},
        'M79': {'ICD Description': 'Other soft tissue disorders, not elsewhere',
             'Number with code in devt cohort': 930,
             'Number with code in frail cohort': 402,
             'Points awarded': 1.1,
             'devt percentage': 4.2,
             'frail percentage': 8.2},
        'M80': {'ICD Description': 'Osteoporosis with pathological fracture',
             'Number with code in devt cohort': 177,
             'Number with code in frail cohort': 83,
             'Points awarded': 0.8,
             'devt percentage': 0.8,
             'frail percentage': 1.7},
        'M81': {'ICD Description': 'Osteoporosis without pathological fracture',
             'Number with code in devt cohort': 1660,
             'Number with code in frail cohort': 682,
             'Points awarded': 1.4,
             'devt percentage': 7.5,
             'frail percentage': 13.9},
        'N17': {'ICD Description': 'Acute renal failure',
             'Number with code in devt cohort': 3454,
             'Number with code in frail cohort': 1713,
             'Points awarded': 1.8,
             'devt percentage': 15.6,
             'frail percentage': 34.9},
        'N18': {'ICD Description': 'Chronic renal failure',
             'Number with code in devt cohort': 3564,
             'Number with code in frail cohort': 1354,
             'Points awarded': 1.4,
             'devt percentage': 16.1,
             'frail percentage': 27.6},
        'N19': {'ICD Description': 'Unspecified renal failure',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 93,
             'Points awarded': 1.6,
             'devt percentage': 1.0,
             'frail percentage': 1.9},
        'N20': {'ICD Description': 'Calculus of kidney and ureter',
             'Number with code in devt cohort': 133,
             'Number with code in frail cohort': 54,
             'Points awarded': 0.7,
             'devt percentage': 0.6,
             'frail percentage': 1.1},
        'N28': {'ICD Description': 'Other disorders of kidney and ureter, not',
             'Number with code in devt cohort': 399,
             'Number with code in frail cohort': 172,
             'Points awarded': 1.3,
             'devt percentage': 1.8,
             'frail percentage': 3.5},
        'N39': {'ICD Description': 'Other disorders of urinary system (includes',
             'Number with code in devt cohort': 3852,
             'Number with code in frail cohort': 2233,
             'Points awarded': 3.2,
             'devt percentage': 17.4,
             'frail percentage': 45.5},
        'R00': {'ICD Description': 'Abnormalities of heart beat',
             'Number with code in devt cohort': 1284,
             'Number with code in frail cohort': 481,
             'Points awarded': 0.7,
             'devt percentage': 5.8,
             'frail percentage': 9.8},
        'R02': {'ICD Description': 'Gangrene, not elsewhere classified',
             'Number with code in devt cohort': 155,
             'Number with code in frail cohort': 83,
             'Points awarded': 1.0,
             'devt percentage': 0.7,
             'frail percentage': 1.7},
        'R11': {'ICD Description': 'Nausea and vomiting',
             'Number with code in devt cohort': 1196,
             'Number with code in frail cohort': 451,
             'Points awarded': 0.3,
             'devt percentage': 5.4,
             'frail percentage': 9.2},
        'R13': {'ICD Description': 'Dysphagia',
             'Number with code in devt cohort': 731,
             'Number with code in frail cohort': 324,
             'Points awarded': 0.8,
             'devt percentage': 3.3,
             'frail percentage': 6.6},
        'R26': {'ICD Description': 'Abnormalities of gait and mobility',
             'Number with code in devt cohort': 1882,
             'Number with code in frail cohort': 1114,
             'Points awarded': 2.6,
             'devt percentage': 8.5,
             'frail percentage': 22.7},
        'R29': {'ICD Description': 'Other symptoms and signs involving the',
             'Number with code in devt cohort': 4140,
             'Number with code in frail cohort': 2429,
             'Points awarded': 3.6,
             'devt percentage': 18.7,
             'frail percentage': 49.5},
        'R31': {'ICD Description': 'Unspecified haematuria',
             'Number with code in devt cohort': 708,
             'Number with code in frail cohort': 309,
             'Points awarded': 3.0,
             'devt percentage': 3.2,
             'frail percentage': 6.3},
        'R32': {'ICD Description': 'Unspecified urinary incontinence',
             'Number with code in devt cohort': 841,
             'Number with code in frail cohort': 461,
             'Points awarded': 1.2,
             'devt percentage': 3.8,
             'frail percentage': 9.4},
        'R33': {'ICD Description': 'Retention of urine',
             'Number with code in devt cohort': 1705,
             'Number with code in frail cohort': 824,
             'Points awarded': 1.3,
             'devt percentage': 7.7,
             'frail percentage': 16.8},
        'R40': {'ICD Description': 'Somnolence, stupor and coma',
             'Number with code in devt cohort': 266,
             'Number with code in frail cohort': 177,
             'Points awarded': 2.5,
             'devt percentage': 1.2,
             'frail percentage': 3.6},
        'R41': {'ICD Description': 'Other symptoms and signs involving',
             'Number with code in devt cohort': 2037,
             'Number with code in frail cohort': 1222,
             'Points awarded': 2.7,
             'devt percentage': 9.2,
             'frail percentage': 24.9},
        'R44': {'ICD Description': 'Other symptoms and signs involving general',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 128,
             'Points awarded': 1.6,
             'devt percentage': 1.0,
             'frail percentage': 2.6},
        'R45': {'ICD Description': 'Symptoms and signs involving emotional',
             'Number with code in devt cohort': 443,
             'Number with code in frail cohort': 260,
             'Points awarded': 1.2,
             'devt percentage': 2.0,
             'frail percentage': 5.3},
        'R47': {'ICD Description': 'Speech disturbances, not elsewhere classified',
             'Number with code in devt cohort': 421,
             'Number with code in frail cohort': 236,
             'Points awarded': 1.0,
             'devt percentage': 1.9,
             'frail percentage': 4.8},
        'R50': {'ICD Description': 'Fever of unknown origin',
             'Number with code in devt cohort': 354,
             'Number with code in frail cohort': 147,
             'Points awarded': 0.1,
             'devt percentage': 1.6,
             'frail percentage': 3.0},
        'R54': {'ICD Description': 'Senility',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 211,
             'Points awarded': 2.2,
             'devt percentage': 1.5,
             'frail percentage': 4.3},
        'R55': {'ICD Description': 'Syncope and collapse',
             'Number with code in devt cohort': 1439,
             'Number with code in frail cohort': 633,
             'Points awarded': 1.8,
             'devt percentage': 6.5,
             'frail percentage': 12.9},
        'R56': {'ICD Description': 'Convulsions, not elsewhere classified',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 206,
             'Points awarded': 2.6,
             'devt percentage': 1.5,
             'frail percentage': 4.2},
        'R63': {'ICD Description': 'Symptoms and signs concerning food and',
             'Number with code in devt cohort': 1328,
             'Number with code in frail cohort': 564,
             'Points awarded': 0.9,
             'devt percentage': 6.0,
             'frail percentage': 11.5},
        'R69': {'ICD Description': 'Unknown and unspecified causes of',
             'Number with code in devt cohort': 177,
             'Number with code in frail cohort': 103,
             'Points awarded': 1.3,
             'devt percentage': 0.8,
             'frail percentage': 2.1},
        'R79': {'ICD Description': 'Other abnormal findings of blood chemistry',
             'Number with code in devt cohort': 819,
             'Number with code in frail cohort': 324,
             'Points awarded': 0.6,
             'devt percentage': 3.7,
             'frail percentage': 6.6},
        'R94': {'ICD Description': 'Abnormal results of function studies',
             'Number with code in devt cohort': 531,
             'Number with code in frail cohort': 236,
             'Points awarded': 1.4,
             'devt percentage': 2.4,
             'frail percentage': 4.8},
        'S00': {'ICD Description': 'Superficial injury of head',
             'Number with code in devt cohort': 886,
             'Number with code in frail cohort': 569,
             'Points awarded': 3.2,
             'devt percentage': 4.0,
             'frail percentage': 11.6},
        'S01': {'ICD Description': 'Open wound of head',
             'Number with code in devt cohort': 753,
             'Number with code in frail cohort': 407,
             'Points awarded': 1.1,
             'devt percentage': 3.4,
             'frail percentage': 8.3},
        'S06': {'ICD Description': 'Intracranial injury',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 128,
             'Points awarded': 2.4,
             'devt percentage': 1.0,
             'frail percentage': 2.6},
        'S09': {'ICD Description': 'Other and unspecified injuries of head',
             'Number with code in devt cohort': 288,
             'Number with code in frail cohort': 157,
             'Points awarded': 1.2,
             'devt percentage': 1.3,
             'frail percentage': 3.2},
        'S22': {'ICD Description': 'Fracture of rib(s), sternum and thoracic spine',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 113,
             'Points awarded': 1.8,
             'devt percentage': 1.0,
             'frail percentage': 2.3},
        'S32': {'ICD Description': 'Fracture of lumbar spine and pelvis',
             'Number with code in devt cohort': 266,
             'Number with code in frail cohort': 128,
             'Points awarded': 1.4,
             'devt percentage': 1.2,
             'frail percentage': 2.6},
        'S42': {'ICD Description': 'Fracture of shoulder and upper arm',
             'Number with code in devt cohort': 266,
             'Number with code in frail cohort': 142,
             'Points awarded': 2.3,
             'devt percentage': 1.2,
             'frail percentage': 2.9},
        'S51': {'ICD Description': 'Open wound of forearm',
             'Number with code in devt cohort': 177,
             'Number with code in frail cohort': 103,
             'Points awarded': 0.5,
             'devt percentage': 0.8,
             'frail percentage': 2.1},
        'S72': {'ICD Description': 'Fracture of femur',
             'Number with code in devt cohort': 1107,
             'Number with code in frail cohort': 530,
             'Points awarded': 1.4,
             'devt percentage': 5.0,
             'frail percentage': 10.8},
        'S80': {'ICD Description': 'Superficial injury of lower leg',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 152,
             'Points awarded': 2.0,
             'devt percentage': 1.1,
             'frail percentage': 3.1},
        'T83': {'ICD Description': 'Complications of genitourinary prosthetic',
             'Number with code in devt cohort': 244,
             'Number with code in frail cohort': 147,
             'Points awarded': 2.4,
             'devt percentage': 1.1,
             'frail percentage': 3.0},
        'U80': {'ICD Description': 'Agent resistant to penicillin and related',
             'Number with code in devt cohort': 288,
             'Number with code in frail cohort': 177,
             'Points awarded': 0.8,
             'devt percentage': 1.3,
             'frail percentage': 3.6},
        'W01': {'ICD Description': 'Fall on same level from slipping, tripping and',
             'Number with code in devt cohort': 686,
             'Number with code in frail cohort': 270,
             'Points awarded': 0.9,
             'devt percentage': 3.1,
             'frail percentage': 5.5},
        'W06': {'ICD Description': 'Fall involving bed',
             'Number with code in devt cohort': 310,
             'Number with code in frail cohort': 186,
             'Points awarded': 1.1,
             'devt percentage': 1.4,
             'frail percentage': 3.8},
        'W10': {'ICD Description': 'Fall on and from stairs and steps',
             'Number with code in devt cohort': 266,
             'Number with code in frail cohort': 103,
             'Points awarded': 0.9,
             'devt percentage': 1.2,
             'frail percentage': 2.1},
        'W18': {'ICD Description': 'Other fall on same level',
             'Number with code in devt cohort': 642,
             'Number with code in frail cohort': 363,
             'Points awarded': 2.1,
             'devt percentage': 2.9,
             'frail percentage': 7.4},
        'W19': {'ICD Description': 'Unspecified fall',
             'Number with code in devt cohort': 2568,
             'Number with code in frail cohort': 1462,
             'Points awarded': 3.2,
             'devt percentage': 11.6,
             'frail percentage': 29.8},
        'X59': {'ICD Description': 'Exposure to unspecified factor',
             'Number with code in devt cohort': 354,
             'Number with code in frail cohort': 196,
             'Points awarded': 1.5,
             'devt percentage': 1.6,
             'frail percentage': 4.0},
        'Y84': {'ICD Description': 'Other medical procedures as the cause of',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 147,
             'Points awarded': 0.7,
             'devt percentage': 1.5,
             'frail percentage': 3.0},
        'Y95': {'ICD Description': 'Nosocomial condition',
             'Number with code in devt cohort': 753,
             'Number with code in frail cohort': 447,
             'Points awarded': 1.2,
             'devt percentage': 3.4,
             'frail percentage': 9.1},
        'Z22': {'ICD Description': 'Carrier of infectious disease',
             'Number with code in devt cohort': 221,
             'Number with code in frail cohort': 132,
             'Points awarded': 1.7,
             'devt percentage': 1.0,
             'frail percentage': 2.7},
        'Z50': {'ICD Description': 'Care involving use of rehabilitation',
             'Number with code in devt cohort': 354,
             'Number with code in frail cohort': 196,
             'Points awarded': 2.1,
             'devt percentage': 1.6,
             'frail percentage': 4.0},
        'Z60': {'ICD Description': 'Problems related to social environment',
             'Number with code in devt cohort': 487,
             'Number with code in frail cohort': 240,
             'Points awarded': 1.8,
             'devt percentage': 2.2,
             'frail percentage': 4.9},
        'Z73': {'ICD Description': 'Problems related to life-management',
             'Number with code in devt cohort': 421,
             'Number with code in frail cohort': 250,
             'Points awarded': 0.6,
             'devt percentage': 1.9,
             'frail percentage': 5.1},
        'Z74': {'ICD Description': 'Problems related to care-provider dependency',
             'Number with code in devt cohort': 332,
             'Number with code in frail cohort': 201,
             'Points awarded': 1.1,
             'devt percentage': 1.5,
             'frail percentage': 4.1},
        'Z75': {'ICD Description': 'Problems related to medical facilities and',
             'Number with code in devt cohort': 642,
             'Number with code in frail cohort': 437,
             'Points awarded': 2.0,
             'devt percentage': 2.9,
             'frail percentage': 8.9},
        'Z87': {'ICD Description': 'Personal history of other diseases and',
             'Number with code in devt cohort': 2790,
             'Number with code in frail cohort': 1197,
             'Points awarded': 1.5,
             'devt percentage': 12.6,
             'frail percentage': 24.4},
        'Z91': {'ICD Description': 'Personal history of risk-factors, not elsewhere',
             'Number with code in devt cohort': 443,
             'Number with code in frail cohort': 182,
             'Points awarded': 0.5,
             'devt percentage': 2.0,
             'frail percentage': 3.7},
        'Z93': {'ICD Description': 'Artificial opening status',
             'Number with code in devt cohort': 443,
             'Number with code in frail cohort': 162,
             'Points awarded': 1.0,
             'devt percentage': 2.0,
             'frail percentage': 3.3},
        'Z99': {'ICD Description': 'Dependence on enabling machines and',
             'Number with code in devt cohort': 399,
             'Number with code in frail cohort': 167,
             'Points awarded': 0.8,
             'devt percentage': 1.8,
             'frail percentage': 3.4}
    }


    return hfrs_weights



# import pdfplumber # Causes cryptography error ;(
# # AttributeError: 'cryptography.hazmat.primitives.asymmetric.dh.DHParameterNumbers' object has no attribute '_p'
# import re
#
# def extract_hfrs_weights(pdf_path):
#     hfrs_weights = {}
#     with pdfplumber.open(pdf_path) as pdf:
#
#         for page in pdf.pages[6:11]:  # Table A2 spans roughly these pages
#             text = page.extract_text()
#             # print(f"PAGE {page}")
#             # print(f"{text}")
#
#             lines = text.split("\n")
#             for line in lines:
#                 pattern = r"^([A-Z][0-9A-Z\.]+)\s+(.+?)\s+(\d{1,3}(?:,\d{3})*|\d+)\s+([\d·\.]+)%\s+(\d{1,3}(?:,\d{3})*|\d+)\s+([\d·\.]+)%\s+([\d·\.]+)$"
#                 match = re.match(pattern, line)
#                 # Does not match numbers with commas,
#                 # R00 Abnormalities of heart beat 1,284 5·8% 481 9·8% 0·7
#                 # F32 Depressive episode 1395 6·3% 613 12·5% 0·5
#                 #match = re.match(r"^([A-Z0-9\.]+)\s+([A-Za-z].*?)\s+(\d+)\s+([\d·\.]+)%\s+(\d+)\s+([\d·\.]+)%\s+([\d·\.]+)", line)
#                 if match:
#                     code, desc, n_dev, pct_dev, n_frail, pct_frail, points = match.groups()
#
#                     # Replace any commas with nothing to remove
#                     n_dev = int(n_dev.replace(",", ""))
#                     n_frail = int(n_frail.replace(",", ""))
#
#                     pct_dev = float(pct_dev.replace("·", "."))
#                     pct_frail = float(pct_frail.replace("·", "."))
#                     points = float(points.replace("·", "."))
#                     hfrs_weights[code] = {
#                         "ICD Description": desc.strip(),
#                         "Number with code in devt cohort": n_dev,
#                         "devt percentage": pct_dev,
#                         "Number with code in frail cohort": n_frail,
#                         "frail percentage": pct_frail,
#                         "Points awarded": points,
#                     }
#                     # print(f"  {code}")
#     return hfrs_weights


# from pprint import pprint

def main():
    # Loads from in-memory
    weights = get_hfrs_weights()
    print(f"Loaded {len(weights)} ICD-10 clusters for HFRS.")
    print("\nExample (G81):")
    from pprint import pprint
    pprint(weights["G81"])

    # # Loads PDF and reads from "file" (quite difficult regex)
    # weights = extract_hfrs_weights("../refs/Frailty_Appendix.pdf")
    # print(f"Loaded {len(weights)} ICD-10 clusters for HFRS.")
    # #print(f"{weights}")
    # # pprint(weights)

# Example usage:
if __name__ == "__main__":
    main()